theme = "apollo"
base_url = "https://christovis.github.io/"
title = "#CB"
description = "This is an example description"
taxonomies = [{ name = "tags" }]
compile_sass = true
#minify_html = true

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "ayu-dark", filename = "syntax-theme-dark.css" },
  { theme = "ayu-light", filename = "syntax-theme-light.css" },
]

[extra]
theme = "toggle"  # light, dark, auto, toggle
favicon = "static/icons/favicon.ico"
fancy_code = true
mathjax = true
mathjax_dollar_inline_enable = true
repo_url = "https://github.com/Christovis/christovis.github.io/tree/main/content/"

socials = [
  # Configure socials here
    { name = "github", url = "https://github.com/Christovis", icon = "github" },
    { name = "mastodon", url = "https://mastodon.green/@chrbecker@eupolicy.social", icon = "mastodon" },
    { name = "pixelfed", url = "https://pixelfed.social/i/web/profile/789250781975312794", icon = "pixelfed" },
]
menu = [
  # Configure menu bar here
    { name = "/software", url = "/software", weight = 1 },
    { name = "/talks", url = "/talks", weight = 2 },
    { name = "/posts", url = "/posts", weight = 3 },
]
